version: '3.9'
services:
  proxy:
    container_name: nekochan-proxy
    build: ./docker/nginx
    ports:
      - '8000:80'
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html
  app:
    container_name: nekochan-app
    build: ./docker/php
    volumes:
      - ./docker/php/php.ini:/usr/local/php/php.ini
      - ./src:/var/www/html
  db:
    container_name: nekochan-db
    build: ./docker/mysql
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - nekochan-db-volume:/var/lib/mysql
    platform: linux/amd64
    environment:
      - MYSQL_DATABASE=nekochan
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - TZ=Asia/Tokyo
volumes:
  nekochan-db-volume: